apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec: 
      containers:
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.port }}
          - name: http-metrics
            containerPort: {{ .Values.port }}
        env:
        - name: MONGODB_URI
          value: "mongodb+srv://root:hello123@vdt.2w2zlck.mongodb.net/?retryWrites=true&w=majority&appName=vdt"
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi" 
            cpu: "100m"